### PR TITLE
Added Restore the permutations by merger

### PR DESCRIPTION
**Pull request by BirajCoder**
Added the python code for Restore the permutations by merger problem 1385B.
Check the accepted image below.
image

Also it would be helpful if you could add the hacktoberfest accepted label in while merging , Thank You.

### CODE REVIEW

**Comment by gouravkhunger** [comment]
Thanks for taking the time to contribute :) I would love to merge the PR but, I would like to mention that the file you committed it empty 😅. I can see the image of the code, but please add the code as outlined in the CONTRIBUTING.md file. Thanks again :)

**Comment by BirajCoder** [comment]
Sorry I added the code and somehow it got misplaced I will add it again soon, sorry for the trouble

**Review by BirajCoder — COMMENTED** [review]
Added the code, Check it now

**Comment by gouravkhunger** [comment]
Yeah, I checked it. But I also tested it and it gives me the wrong output than as expected in the example test case. On further checking, I found you have given the code for problem 1385C. Make It Good rather than problem 1385B. Restore the permutations by merger. This is getting a bit confusing. Please check the screenshot you attached and the code you submitted. I hope you will look into the matter further.

I am closing this PR because of the confusion. I request you to make a new PR if you wish to contribute. Thank you :)

**Pull request closed without merging**
